import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import RootStyleRegistry from './registry';

const inter = Inter({ display: 'swap', subsets: ['latin'], variable: '--font-inter' });
const hira = localFont({
  src: '../assets/fonts/Hiragino.otf',
  display: 'swap',
  variable: '--font-hira',
});

export const metadata: Metadata = {
  title: 'Health App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${hira.variable}`}>
        <RootStyleRegistry>{children}</RootStyleRegistry>
      </body>
    </html>
  );
}
